{
 "title": "Analysis",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "P99 Decision Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(publisher_xt_decision_latency_seconds_bucket[30m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Decision Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(publisher_xt_decision_latency_seconds_bucket[30m]))\n/\nsum(increase(publisher_xt_decision_latency_seconds_bucket[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Inclusion Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(publisher_xt_block_inclusion_latency_seconds_bucket[30m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Inclusion Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(publisher_xt_block_inclusion_latency_seconds_sum[30m]))\n/\nsum(increase(publisher_xt_block_inclusion_latency_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}